# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Recreate Java Staging Deployment 

on:
  push:
    branches:
      - "release/*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK for Maven Deployment 
        uses: actions/setup-java@v3
        with:
          cache: maven
          java-version: "8.0.332+9"
          distribution: "temurin"
          server-id: ossrh
          server-username: MVN_USERNAME
          server-password: MVN_PASSWORD
        env:
          MVN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Install MAVEN dependencies
        run: mvn dependency:resolve -B -U

      - name: Deploy Maven packages
        run: mvn -B deploy -Prelease
        env:
          MVN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
